### ISSUE TITLE
conversion.rb:18:in `block in do_conversions': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by rambda** [KoBeWi/Another-Godot-4-Converter#1]
Can't read Ruby, don't quite understand what's going on. 

> 
> Converting file: C:/sources/PnxG4/addons/AutoExportVersion/AutoExportVersion.gd (162/655)
> C:/sources/Another-Godot-4-Converter/conversion.rb:18:in `block in do_conversions': undefined method `[]' for nil:NilClass (NoMethodError)
> 
>                 type = line.match(%r{extends (\\w+)[:|\\s]})[1]\r
>                                                           ^^^
>         from C:/sources/Another-Godot-4-Converter/conversion.rb:7:in `collect!'
>         from C:/sources/Another-Godot-4-Converter/conversion.rb:7:in `do_conversions'
>         from C:/sources/Another-Godot-4-Converter/scripts.rb:4:in `initialize'
>         from main.rb:74:in `new'
>         from main.rb:74:in `block in <main>'
>         from main.rb:72:in `each'
>         from main.rb:72:in `<main>'

**Comment by KoBeWi** [comment]
Thanks for the report, fixed in 289534aa54763cee2196966504c7345fce79ba4e
